XBMC_USER: "{{ xbmc.user }}"
THIS_FILE: $0
SCRIPT_VERSION: "0.91"
VIDEO_DRIVER: ""
HOME_DIRECTORY: "/home/{{ XBMC_USER }}/"
KERNEL_DIRECTORY: "{{ HOME_DIRECTORY }}kernel/"
TEMP_DIRECTORY: "{{ HOME_DIRECTORY }}temp/"
ENVIRONMENT_FILE: "/etc/environment"
CRONTAB_FILE: "/etc/crontab"
DIST_UPGRADE_FILE: "/etc/cron.d/dist_upgrade.sh"
DIST_UPGRADE_LOG_FILE: "/var/log/updates.log"
XBMC_ADDONS_DIR: "{{ HOME_DIRECTORY }}.xbmc/addons/"
XBMC_USERDATA_DIR: "{{ HOME_DIRECTORY }}.xbmc/userdata/"
XBMC_KEYMAPS_DIR: "{{ XBMC_USERDATA_DIR }}keymaps/"
XBMC_ADVANCEDSETTINGS_FILE: "{{ XBMC_USERDATA_DIR }}advancedsettings.xml"
XBMC_INIT_CONF_FILE: "/etc/init/xbmc.conf"
XBMC_XSESSION_FILE: "/home/xbmc/.xsession"
UPSTART_JOB_FILE: "/lib/init/upstart-job"
XWRAPPER_FILE: "/etc/X11/Xwrapper.config"
GRUB_CONFIG_FILE: "/etc/default/grub"
GRUB_HEADER_FILE: "/etc/grub.d/00_header"
SYSTEM_LIMITS_FILE: "/etc/security/limits.conf"
INITRAMFS_SPLASH_FILE: "/etc/initramfs-tools/conf.d/splash"
INITRAMFS_MODULES_FILE: "/etc/initramfs-tools/modules"
XWRAPPER_CONFIG_FILE: "/etc/X11/Xwrapper.config"
MODULES_FILE: "/etc/modules"
REMOTE_WAKEUP_RULES_FILE: "/etc/udev/rules.d/90-enable-remote-wakeup.rules"
AUTO_MOUNT_RULES_FILE: "/etc/udev/rules.d/media-by-label-auto-mount.rules"
SYSCTL_CONF_FILE: "/etc/sysctl.conf"
RSYSLOG_FILE: "/etc/init/rsyslog.conf"
POWERMANAGEMENT_DIR: "/etc/polkit-1/localauthority/50-local.d/"
DOWNLOAD_URL: "https://github.com/Albinoman887/xbmc-ubuntu-minimal/raw/master/12.10/download/"
XBMC_PPA: "{{ xbmc.repo }}"
#XBMC_PPA: "ppa:team-xbmc/xbmc-nightly"
HTS_TVHEADEND_PPA: "ppa:jabbors/hts-stable"
OSCAM_PPA: "ppa:oscam/ppa"
XSWAT_PPA: "ppa:ubuntu-x-swat/x-updates"
MESA_PPA: "ppa:wsnipex/mesa"
GFX_CARD: "NVIDIA"
#GFX_CARD: "AMD"
#GFX_CARD: "Intel"
RESOLUTION: "{{ xbmc.resolution }}"

