---
- name: install XBMC
  hosts:
    - xbmc
  vars_prompt:
    - name: "xbmc.passwd"
      prompt: "Password"
      private: true
  vars:
    - xbmc:
        user: "xbmc"
        repo: "ppa:team-xbmc/xbmc-nightly"
        resolution: "1920x1080"
  roles:
    - xbmc
