---
- name: install XBMC
  hosts:
    - xbmc
  vars_prompt:
    - name: "xbmc.passwd"
      prompt: "Password"
      private: true
  vars:
    - xbmc:
        user: "xbmc"
        repo: "deb http://ppa.launchpad.net/team-xbmc/xbmc-nightly/ubuntu saucy main "
        resolution: "1920x1080"
  roles:
    - xbmc
